[package]
name = "browser"
version = "0.1.0"
edition = "2024"

[dependencies]
glib = "0.21.4"
gtk4 = { version = "0.10.1", features = ["v4_20"] }
webkit6 = "0.5.0"

[build-dependencies]
glib-build-tools = "0.21.0"
